fix(examples): Fix error TS6305 when running `npm run build` on examples.
```
Error TS6305: Output file '/home/martin/.../auth-antd/vite.config.d.ts' has not been built from source file '/home/martin/.../auth-antd/vite.config.ts'.
  The file is in the program because:
    Matched by include pattern 'vite.config.ts' in '/home/martin/.../auth-antd/tsconfig.json'

  tsconfig.json:19:22
    19   "include": ["src", "vite.config.ts"],
                            ~~~~~~~~~~~~~~~~
    File is matched by include pattern specified here.
```